            - name: Java Automatic Release
  # You may pin to the exact commit or the version.
  # uses: Fulminazzo/java-automatic-release@1d23fecb023b22a32799f96e8fa47fecf2ae7620
  uses: Fulminazzo/java-automatic-release@v2
  with:
    # The Java version to use when setting up Java.
    java-version: # optional, default is 11
          
